openapi: 3.0.3
info:
  title: Anime List Manager API
  description: API for managing anime lists imported from MyAnimeList
  version: 1.0.0
servers:
  - url: http://localhost:3001
    description: Development server

tags:
  - name: Anime
    description: Anime list operations
  - name: Tags
    description: Tag management
  - name: Import
    description: Import/Export operations

paths:
  /anime:
    get:
      operationId: getAnimeList
      tags:
        - Anime
      summary: Get all anime with optional filters
      parameters:
        - name: tags
          in: query
          description: Comma-separated tag IDs to filter by
          schema:
            type: string
        - name: minScore
          in: query
          description: Minimum score filter
          schema:
            type: integer
            minimum: 1
            maximum: 10
        - name: maxScore
          in: query
          description: Maximum score filter
          schema:
            type: integer
            minimum: 1
            maximum: 10
        - name: search
          in: query
          description: Search by title (case-insensitive)
          schema:
            type: string
        - name: sortBy
          in: query
          description: Field to sort by
          schema:
            type: string
            enum: [title, myScore, type, updatedAt]
            default: title
        - name: sortOrder
          in: query
          description: Sort order
          schema:
            type: string
            enum: [asc, desc]
            default: asc
      responses:
        '200':
          description: List of anime
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Anime'

  /anime/{id}:
    get:
      operationId: getAnimeById
      tags:
        - Anime
      summary: Get a single anime by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Anime details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Anime'
        '404':
          description: Anime not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      operationId: deleteAnime
      tags:
        - Anime
      summary: Delete an anime entry
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Anime deleted successfully
        '404':
          description: Anime not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /anime/{id}/tags:
    post:
      operationId: setAnimeTags
      tags:
        - Anime
      summary: Set custom tags for an anime (replaces existing custom tags)
      description: |
        Accepts a list of tag names. The backend will:
        1. Compare with existing custom tags
        2. Remove tags not in the list
        3. Add new tags (create if name doesn't exist)
        4. Status tags are NOT affected
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetTagsRequest'
      responses:
        '200':
          description: Tags updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Anime'
        '404':
          description: Anime not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /tags:
    get:
      operationId: getTags
      tags:
        - Tags
      summary: Get all tags
      parameters:
        - name: includeStatus
          in: query
          description: Include status tags in response
          schema:
            type: boolean
            default: true
      responses:
        '200':
          description: List of tags
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tag'

  /tags/{id}:
    put:
      operationId: updateTag
      tags:
        - Tags
      summary: Update a tag
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTag'
      responses:
        '200':
          description: Tag updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
        '400':
          description: Invalid request (e.g., cannot modify status tags)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Tag not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      operationId: deleteTag
      tags:
        - Tags
      summary: Delete a tag
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Tag deleted successfully
        '400':
          description: Cannot delete status tags
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Tag not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /import:
    post:
      operationId: importMalXml
      tags:
        - Import
      summary: Import anime list from MAL XML export
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: MAL XML export file
              required:
                - file
      responses:
        '200':
          description: Import completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImportResult'
        '400':
          description: Invalid XML file
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Anime:
      type: object
      properties:
        id:
          type: integer
        malId:
          type: integer
        title:
          type: string
        type:
          type: string
          enum: [TV, Movie, OVA, Special, ONA, Music]
        episodes:
          type: integer
          nullable: true
        myScore:
          type: integer
          minimum: 0
          maximum: 10
        myWatchedEpisodes:
          type: integer
        myStartDate:
          type: string
          format: date
          nullable: true
        myFinishDate:
          type: string
          format: date
          nullable: true
        myRewatching:
          type: boolean
        myRewatchingEp:
          type: integer
        myLastUpdated:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
      required:
        - id
        - malId
        - title
        - myScore
        - myWatchedEpisodes
        - myRewatching
        - myRewatchingEp
        - tags

    Tag:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        color:
          type: string
          description: Hex color code
        isStatus:
          type: boolean
          description: If true, this is a status tag (managed by import)
      required:
        - id
        - name
        - color
        - isStatus

    UpdateTag:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 50
        color:
          type: string
          pattern: '^#[0-9A-Fa-f]{6}$'

    SetTagsRequest:
      type: object
      properties:
        tags:
          type: array
          items:
            type: string
          description: Complete list of custom tag names for this anime
      required:
        - tags

    ImportResult:
      type: object
      properties:
        created:
          type: integer
          description: Number of new anime entries created
        updated:
          type: integer
          description: Number of existing entries updated
        failed:
          type: integer
          description: Number of entries that failed to import
        errors:
          type: array
          items:
            type: string
          description: Error messages for failed entries
      required:
        - created
        - updated
        - failed
        - errors

    Error:
      type: object
      properties:
        message:
          type: string
        statusCode:
          type: integer
      required:
        - message
        - statusCode
